"""create telemetry table

Revision ID: 395c39b812fb
Revises: 400bea72149b
Create Date: 2026-06-04 00:09:49.560252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '395c39b812fb'
down_revision: Union[str, Sequence[str], None] = '400bea72149b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('rssi', sa.Integer(), nullable=True))
    op.add_column('telemetry', sa.Column('snr', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('telemetry', 'latitude',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('telemetry', 'longitude',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('telemetry', 'altitude',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('telemetry', 'roll',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('telemetry', 'pitch',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('telemetry', 'yaw',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('telemetry', 'battery',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('telemetry', 'speed',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.create_index(op.f('ix_telemetry_created_at'), 'telemetry', ['created_at'], unique=False)
    op.create_index(op.f('ix_telemetry_drone_id'), 'telemetry', ['drone_id'], unique=False)
    op.create_index(op.f('ix_telemetry_id'), 'telemetry', ['id'], unique=False)
    op.drop_index(op.f('idx_telemetry_drone_timestamp'), table_name='telemetry')
    op.drop_column('telemetry', 'timestamp')
    op.drop_column('telemetry', 'signal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('signal', mysql.FLOAT(), nullable=False))
    op.add_column('telemetry', sa.Column('timestamp', mysql.DATETIME(), nullable=False))
    op.drop_index(op.f('ix_telemetry_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_drone_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_created_at'), table_name='telemetry')
    op.create_index(op.f('idx_telemetry_drone_timestamp'), 'telemetry', ['drone_id', 'timestamp'], unique=False)
    op.alter_column('telemetry', 'speed',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('telemetry', 'battery',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('telemetry', 'yaw',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('telemetry', 'pitch',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('telemetry', 'roll',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('telemetry', 'altitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('telemetry', 'longitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('telemetry', 'latitude',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.drop_column('telemetry', 'created_at')
    op.drop_column('telemetry', 'snr')
    op.drop_column('telemetry', 'rssi')
    # ### end Alembic commands ###
