"""initial_schema

Revision ID: e7e7f9818c71
Revises: 2f47a2eeebcb
Create Date: 2026-06-03 21:29:36.500117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e7e7f9818c71'
down_revision: Union[str, Sequence[str], None] = '2f47a2eeebcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'SUCCESS', 'FAILED', name='command_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drone_state',
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('roll', sa.Float(), nullable=True),
    sa.Column('pitch', sa.Float(), nullable=True),
    sa.Column('yaw', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('battery', sa.Float(), nullable=True),
    sa.Column('signal', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.PrimaryKeyConstraint('drone_id')
    )
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.Column('mission_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'RUNNING', 'COMPLETED', 'FAILED', name='mission_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('max_altitude', sa.Float(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waypoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('drones', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('drones', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('drones', sa.Column('firmware_version', sa.String(length=50), nullable=True))
    op.add_column('drones', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.alter_column('drones', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('ONLINE', 'OFFLINE', 'FLYING', 'MISSION', 'ERROR', name='drone_status'),
               existing_nullable=False)
    op.create_foreign_key(None, 'drones', 'users', ['user_id'], ['id'])
    op.add_column('telemetry', sa.Column('drone_id', sa.Integer(), nullable=False))
    op.add_column('telemetry', sa.Column('roll', sa.Float(), nullable=False))
    op.add_column('telemetry', sa.Column('pitch', sa.Float(), nullable=False))
    op.add_column('telemetry', sa.Column('yaw', sa.Float(), nullable=False))
    op.add_column('telemetry', sa.Column('speed', sa.Float(), nullable=False))
    op.add_column('telemetry', sa.Column('signal', sa.Float(), nullable=False))
    op.add_column('telemetry', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.create_index('idx_telemetry_drone_timestamp', 'telemetry', ['drone_id', 'timestamp'], unique=False)
    op.create_foreign_key(None, 'telemetry', 'drones', ['drone_id'], ['id'])
    op.drop_column('telemetry', 'created_at')
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'PILOT', 'OPERATOR', name='user_role'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'role')
    op.drop_column('users', 'email')
    op.add_column('telemetry', sa.Column('created_at', mysql.DATETIME(), nullable=False))
    op.drop_constraint(None, 'telemetry', type_='foreignkey')
    op.drop_index('idx_telemetry_drone_timestamp', table_name='telemetry')
    op.drop_column('telemetry', 'timestamp')
    op.drop_column('telemetry', 'signal')
    op.drop_column('telemetry', 'speed')
    op.drop_column('telemetry', 'yaw')
    op.drop_column('telemetry', 'pitch')
    op.drop_column('telemetry', 'roll')
    op.drop_column('telemetry', 'drone_id')
    op.drop_constraint(None, 'drones', type_='foreignkey')
    op.alter_column('drones', 'status',
               existing_type=sa.Enum('ONLINE', 'OFFLINE', 'FLYING', 'MISSION', 'ERROR', name='drone_status'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('drones', 'last_seen')
    op.drop_column('drones', 'firmware_version')
    op.drop_column('drones', 'model')
    op.drop_column('drones', 'user_id')
    op.drop_table('waypoints')
    op.drop_table('flight_logs')
    op.drop_table('missions')
    op.drop_table('drone_state')
    op.drop_table('commands')
    # ### end Alembic commands ###
